[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.36"
optimizer = true
optimizer_runs = 999999

# For dependencies
remappings = [
    'forge-std/=lib/forge-std/src/',
]

[lint]

exclude_lints = [
    'custom-errors',
    'encode-packed-collision',
    'inline-assembly',
    'interface-file-naming',
    'interface-naming',
    'internal-function-used-once',
    'literal-instead-of-constant',
    'missing-inheritance',
    'multi-contract-file',
    'reentrancy-events',
    'todo-comment',
    'unused-return',
]
